name: Petclinic CI
on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Generate docker images
      run: mvn spring-boot:build-image --file pom.xml -X -Pk8s -DREPOSITORY_PREFIX=${{ secrets.DOCKER_HUB_USERNAME }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set DRY_RUN for test branch
      if: github.ref == 'refs/heads/test'
      run: echo "DRY_RUN=true" >> $GITHUB_ENV
    
    - name: Push Docker images
      run: ./scripts/pushImages.sh

